from dataclasses import dataclass, field
from typing import List
from datetime import datetime
# -----------------------------
# Request Schema
# -----------------------------

@dataclass
class Remark:
    """
    A single RM remark associated with a single policy.
    """

    timestamp: datetime
    author : str
    text : str


@dataclass
class PolicyContext:
    """
    Everything the LLM needs to analyze the policy
    """

    policy_number: str
    # customer_id: str

    # Base probability by LSTM
    base_probability : float

    # Structured Policy Information
    current_policy : dict

    # # Insights extracted from customer history
    historical_insights: List[str]

    # RM remarks in chronological order
    remarks: List[Remark]


# ============================================================
# PREDICTION EXPLANATION
# ============================================================

@dataclass
class PredictionExplanation:
    """
    Explains why the predictive model arrived at the base probability
    """

    summary : str

    supporting_factors : List[str]

    risk_factors: List[str]

# ============================================================
# REMARK ADJUSTMENT
# ============================================================

@dataclass
class RemarkAdjustment:
    """
    Impact of a single RM remark.
    """
    remark_index: int
    #Remark index of each remark

    remark: str

    impact: str
    # Positive / Negative / Neutral

    adjustment: int
    # Contribution from -15 to +15

    confidence : str
    # Low / Medium / High

    reasoning : str

    evidence : List[str]
    # Exact phrases from the remark supporting the adjustment


# ============================================================
# RECOMMENDATION
# ============================================================

@dataclass
class Recommendation:

    priority : str
    # Low / Medium / High

    action : str

# ============================================================
# RESPONSE SCHEMA
# ============================================================

@dataclass
class PolicyAnalysisResponse:
    """
    Complete Response generated by the LLM 
    """

    # Explanation of the base probability 
    prediction_explanation : PredictionExplanation

    # Analysis of each RM remark
    remark_adjustments : List[RemarkAdjustment] = field(default_factory=list)

    # Overall reasoning combining the prediction and remarks
    overall_summary : str = ""

    # Suggested action for the renewal manager
    recommendation : Recommendation = None